# referência: https://www.prisma.io/blog/nestjs-prisma-rest-api-7D056s1BmOL0
version: '3.8'
services:
  app:
    build: .
    command: npm run build
    volumes:
      - .:/usr/app
      - ./usr/app/node_modules
    ports:
      - "3000:80"
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      -'5432:5432'

volumes:
  postgres:
    
